import type { RightsTopicData } from "@/types";

export const RIGHTS_TOPICS: RightsTopicData[] = [
  {
    id: "besittningsskydd",
    title: "Besittningsskydd",
    tag: "Grundläggande",
    icon: "Home",
    summary: "Din rätt att bo kvar",
    content: `Enligt 12 kap. 46 § JB har du som hyresgäst rätt att bo kvar i din bostad. Hyresvärden kan bara säga upp dig av de skäl som räknas upp i lagen, t.ex. om du allvarligt misskött lägenheten, om fastigheten ska rivas, eller om hyresvärden behöver lägenheten för eget bruk. Skyddet gäller automatiskt efter att du bott i lägenheten i 2 år.`,
    lawRef: "12 kap. 46 § JB",
  },
  {
    id: "andrahand",
    title: "Andrahandsuthyrning",
    tag: "Viktigt",
    icon: "Users",
    summary: "Rätt att hyra ut i andra hand",
    content: `Du har rätt att hyra ut din lägenhet i andra hand om du har skäliga skäl, t.ex. arbete eller studier på annan ort, provsamboende, eller vård av anhörig. Hyresvärden måste bevilja eller neka inom 4 veckor. Vägrar de utan skäl kan du ansöka om tillstånd hos Hyresnämnden. Ett avtalsförbud mot andrahand är utan verkan — lagen är tvingande (12 kap. 40 § JB).`,
    lawRef: "12 kap. 40 § JB",
  },
  {
    id: "renovering",
    title: "Renovering & underhåll",
    tag: "Vanlig tvist",
    icon: "Wrench",
    summary: "Vem ansvarar för vad?",
    content: `Hyresvärden ansvarar för att lägenheten är i gott bruksskick under hela hyrestiden (12 kap. 15 § JB). Det inkluderar reparationer av vitvaror, VVS, el och byggnadsdelar. Du som hyresgäst ansvarar normalt för lindriga reparationer och för skador du själv orsakat. Dokumentera alltid lägenhetens skick vid in- och utflyttning med foton.`,
    lawRef: "12 kap. 15 § JB",
  },
  {
    id: "hyreshojning",
    title: "Hyreshöjning",
    tag: "Aktuellt 2025",
    icon: "TrendingUp",
    summary: "Dina rättigheter vid höjning",
    content: `Hyresvärden måste meddela en hyreshöjning minst 3 månader i förväg. Du har rätt att tacka nej och kräva att hyran prövas av Hyresnämnden. Hyran ska vara skälig enligt bruksvärdesprincipen — dvs. jämförbar med hyran för likvärdiga lägenheter i samma område. En indexklausul som ger orimliga höjningar kan alltid prövas (12 kap. 55 § JB).`,
    lawRef: "12 kap. 55 § JB",
  },
  {
    id: "uppsagning",
    title: "Uppsägning & vräkning",
    tag: "Allvarligt",
    icon: "DoorOpen",
    summary: "Vad gäller om du sägs upp?",
    content: `En hyresvärd kan bara vräka dig via Kronofogden efter ett domstolsbeslut. Du har alltid rätt till 1–3 månaders uppsägningstid. Om du bestrider uppsägningen måste du hänskjuta ärendet till Hyresnämnden inom 2 månader. Kontakta alltid Hyresnämnden eller en jurist innan du accepterar en uppsägning.`,
    lawRef: "12 kap. 46–49 §§ JB",
  },
  {
    id: "sambo",
    title: "Sambo & övertagande",
    tag: "Familjerätt",
    icon: "Heart",
    summary: "Rätt att ta över hyresrätten",
    content: `Vid dödsfall eller separation kan en sambo eller make ha rätt att ta över hyresrätten. Det krävs att personen haft sin permanenta bostad i lägenheten och att ett övertagande är skäligt mot hyresvärden. Ansökan görs hos Hyresnämnden. Vid dödsfall ska anmälan göras inom en månad.`,
    lawRef: "12 kap. 33–34 §§ JB",
  },
  {
    id: "fukt-mogel",
    title: "Fukt & mögel",
    tag: "Hälsa",
    icon: "AlertTriangle",
    summary: "Hyresvärdens ansvar för fuktskador",
    content: `Hyresvärden är skyldig att åtgärda fukt- och mögelskador som påverkar din hälsa eller boendets funktion. Anmäl skriftligt och spara kvitto på anmälan. Om hyresvärden inte agerar inom skälig tid kan du anmäla till kommunens miljö- och hälsoskyddsförvaltning, som kan ålägga hyresvärden att åtgärda felet. Du kan även ha rätt till hyresnedsättning under den tid lägenheten är i brister. Stöd i miljöbalken 9 kap. och 12 kap. 15 § JB.`,
    lawRef: "12 kap. 15 § JB, Miljöbalken 9 kap.",
  },
  {
    id: "hyresnedsattning",
    title: "Hyresnedsättning",
    tag: "Ekonomi",
    icon: "TrendingDown",
    summary: "Rätt till sänkt hyra vid brister",
    content: `Om lägenheten har brister som hyresvärden inte åtgärdar inom skälig tid kan du ha rätt till hyresnedsättning (12 kap. 16 § JB). Anmäl alltid skriftligt. Nedsättningen beräknas utifrån hur stor del av lägenheten som är oanvändbar. I akuta fall (t.ex. inget vatten eller värme) kan nedsättningen vara 100%. Spara all kommunikation med hyresvärden som bevis.`,
    lawRef: "12 kap. 16 § JB",
  },
  {
    id: "storning",
    title: "Störningar & grannar",
    tag: "Vanligt",
    icon: "Volume2",
    summary: "Rätt till lugn och ro",
    content: `Du har rätt till ett ostört boende. Om grannar stör kan du anmäla till hyresvärden, som är skyldig att agera. Upprepade störningar från en granne kan leda till att den grannen förlorar sin hyresrätt (12 kap. 25 § JB). Om du själv stör upprepat och inte rättar till det efter tillsägelse kan din hyresrätt sägas upp. Dokumentera störningar med datum och klockslag.`,
    lawRef: "12 kap. 25 § JB",
  },
  {
    id: "inneboende",
    title: "Inneboende",
    tag: "Praktiskt",
    icon: "UserPlus",
    summary: "Rätt att ha inneboende",
    content: `Du har rätt att ha inneboende utan hyresvärdens tillstånd, så länge det inte leder till trångboddhet eller att lägenheten används för annat ändamål. En inneboende är inte part i hyreskontraktet och har inga egna rättigheter gentemot hyresvärden. Du ansvarar för inneboendes agerande i lägenheten.`,
    lawRef: "12 kap. 41 § JB",
  },
  {
    id: "deposition",
    title: "Deposition & handpenning",
    tag: "Ekonomi",
    icon: "Wallet",
    summary: "Regler kring deposition",
    content: `En deposition ska återbetalas inom skälig tid efter att du lämnat lägenheten, normalt inom 1–2 månader. Hyresvärden kan bara hålla inne deposition för faktiska skador du orsakat — inte för normalt slitage. Kräv alltid ett skriftligt kvitto på depositionen och dokumentera lägenhetens skick vid inflyttning. Tvist om deposition avgörs i allmän domstol.`,
    lawRef: "12 kap. JB, Avtalslagen",
  },
  {
    id: "vattenvarme",
    title: "Värme & varmvatten",
    tag: "Grundläggande",
    icon: "Thermometer",
    summary: "Rätt till värme och varmvatten",
    content: `Hyresvärden är skyldig att tillhandahålla tillräcklig värme och varmvatten. Inomhustemperaturen bör vara minst 20°C. Om värme eller varmvatten uteblir har du rätt till hyresnedsättning och kan anmäla till kommunens miljöförvaltning. Anmäl alltid skriftligt och dokumentera temperaturproblem med mätningar och datum.`,
    lawRef: "12 kap. 15 § JB, Miljöbalken",
  },
  {
    id: "rokforbud",
    title: "Rökning & husdjur",
    tag: "Regler",
    icon: "Ban",
    summary: "Vad får hyresvärden bestämma?",
    content: `Hyresvärden kan förbjuda rökning inomhus i hyreskontraktet — detta är ett giltigt villkor. Husdjursförbud i avtal är dock mer komplicerat; ett totalförbud kan vara oskäligt om husdjuret inte stör grannar. Hyresnämnden har i flera fall ansett att husdjursförbud inte kan tillämpas om djuret inte orsakar störningar. Kontakta Hyresnämnden om du är osäker.`,
    lawRef: "12 kap. 19 § JB",
  },
  {
    id: "besiktning",
    title: "Hyresvärdens tillträde",
    tag: "Integritet",
    icon: "Key",
    summary: "När får hyresvärden komma in?",
    content: `Hyresvärden får inte tränga in i din lägenhet utan ditt samtycke, förutom vid akuta situationer (t.ex. brand eller vattenläcka). Vid planerade besiktningar eller reparationer måste hyresvärden meddela dig i förväg med skälig varsel — normalt minst en vecka. Du har rätt att vara hemma vid besiktning. Brott mot detta kan utgöra hemfridsbrott (BrB 4 kap. 6 §).`,
    lawRef: "12 kap. 26 § JB, BrB 4 kap. 6 §",
  },
  {
    id: "hyresforhandling",
    title: "Hyresförhandlingslagen",
    tag: "Kollektiv",
    icon: "Scale",
    summary: "Kollektiva hyresförhandlingar",
    content: `Hyresförhandlingslagen (1978:304) reglerar kollektiva förhandlingar mellan hyresvärdar och hyresgästorganisationer (t.ex. Hyresgästföreningen). Om din fastighet omfattas av ett förhandlingsavtal förhandlas hyran kollektivt. Du kan ändå alltid pröva din individuella hyra mot bruksvärdet i Hyresnämnden. Är du osäker på om din fastighet har förhandlingsavtal — kontakta Hyresgästföreningen.`,
    lawRef: "Hyresförhandlingslagen (1978:304)",
  },
  {
    id: "bostadsrattslagen",
    title: "Bostadsrättslagen",
    tag: "Bostadsrätt",
    icon: "Building",
    summary: "Om du bor i bostadsrätt",
    content: `Bostadsrättslagen (1991:614) gäller om du äger en bostadsrätt. Du betalar månadsavgift till bostadsrättsföreningen istället för hyra. Föreningen ansvarar för yttre underhåll och gemensamma utrymmen. Du ansvarar för lägenhetens inre underhåll. Du kan hyra ut din bostadsrätt i andra hand med styrelsens tillstånd — vägrar styrelsen utan skäl kan du ansöka hos Hyresnämnden.`,
    lawRef: "Bostadsrättslagen (1991:614)",
  },
  {
    id: "hyresnamnden",
    title: "Hyresnämnden",
    tag: "Myndighet",
    icon: "Landmark",
    summary: "Din viktigaste resurs vid tvist",
    content: `Hyresnämnden är en statlig myndighet som kostnadsfritt hanterar tvister mellan hyresgäster och hyresvärdar. Du kan ansöka om prövning av: hyrans skälighet, andrahandstillstånd, uppsägning, renoveringsåtgärder, och mycket mer. Ansökan är gratis och du behöver ingen jurist. Hyresnämndens beslut kan överklagas till Svea hovrätt. Hitta din lokala Hyresnämnd på domstol.se.`,
    lawRef: "Lagen om arrendenämnder och hyresnämnder (1973:188)",
  },
  {
    id: "konsumentratt",
    title: "Konsumenträtt & oskäliga villkor",
    tag: "Avtal",
    icon: "FileX",
    summary: "Oskäliga avtalsvillkor är ogiltiga",
    content: `Villkor i hyresavtal som strider mot tvingande lagstiftning är ogiltiga, även om du skrivit under. Exempel på ogiltiga villkor: förbud mot att ha inneboende (om det inte stör), krav på att du betalar för hyresvärdens normala underhåll, avtalsklausuler som inskränker din rätt till Hyresnämnden. Lagen om avtalsvillkor i konsumentförhållanden (1994:1512) och 36 § Avtalslagen skyddar dig mot oskäliga villkor.`,
    lawRef: "36 § Avtalslagen, Lag (1994:1512) om avtalsvillkor",
  },
  {
    id: "forvaltningsratt",
    title: "Socialtjänst & bostadsbidrag",
    tag: "Ekonomi",
    icon: "HeartHandshake",
    summary: "Ekonomiskt stöd för boende",
    content: `Om du har svårt att betala hyran kan du ha rätt till bostadsbidrag via Försäkringskassan (gäller barnfamiljer och unga under 29 år) eller bostadstillägg (pensionärer). Socialtjänsten kan ge ekonomiskt bistånd vid akut bostadskris. Kontakta kommunens socialtjänst om du riskerar vräkning — de har en skyldighet att hjälpa barnfamiljer och utsatta grupper. Socialtjänstlagen 4 kap. 1 §.`,
    lawRef: "Socialtjänstlagen 4 kap. 1 §, Bostadsbidragslagen",
  },
  {
    id: "diskriminering",
    title: "Diskriminering",
    tag: "Rättigheter",
    icon: "Shield",
    summary: "Skydd mot diskriminering",
    content: `Det är förbjudet att diskriminera hyresgäster eller bostadssökande på grund av kön, könsöverskridande identitet, etnisk tillhörighet, religion, funktionsnedsättning, sexuell läggning eller ålder (Diskrimineringslagen 2008:567). Om du nekas en bostad eller behandlas sämre av dessa skäl kan du anmäla till Diskrimineringsombudsmannen (DO). Vid diskriminering kan du ha rätt till diskrimineringsersättning.`,
    lawRef: "Diskrimineringslagen (2008:567)",
  },
];
